### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by KubiRemPL** [eutropius225/MultiblockTweaker#1]
As i sad mod is great but we need some help in some aspects. Mayby docs or discord.

**Comment by Eutro** [comment]
Official Crafttweaker docs are coming soon! Until then your best option is looking at the javadocs in the files in `src/main/java/crafttweaker/`. I'll keep this issue open until the official docs are added.

**Comment by eutro** [comment]
Official Crafttweaker docs are coming soon! Until then your best option is looking at the javadocs in the files in `src/main/java/eutros/multiblocktweaker/crafttweaker/`. I'll keep this issue open until the official docs are added.
