### ISSUE TITLE
[Feature Request] Support steam machines

### ISSUE THREAD

**Issue by friendlyhj** [eutropius225/MultiblockTweaker#10]

**Comment by eutro** [comment]
Closing this. Setting the recipe EU/t to negative makes the recipe generate energy already.

**Comment by friendlyhj** [comment]
Oh, sorry. I'm posting issue for my friend. And I misunderstood his meaning... The actual feature request is steam boilers.

**Comment by eutro** [comment]
What issues are they having? What do steam boilers need that is not possible currently?
