### ISSUE TITLE
Minecraft crashes on startup with a java.lang.NoClassDefFoundError: eutros/multiblocktweaker/crafttweaker/gtwrap/interfaces/ISound exception

### ISSUE THREAD

**Issue by levicc00123** [eutropius225/MultiblockTweaker#32]
CraftTweaker 4.1.20.685
MultiblockTweaker 1.12.2-stable-1.7.1
Gregtech CE: Unofficial 2.5.3-beta

logs:
[crash-2023-03-06_07.31.37-client.txt](https://github.com/eutro/MultiblockTweaker/files/10899413/crash-2023-03-06_07.31.37-client.txt)
[latest.log](https://github.com/eutro/MultiblockTweaker/files/10899416/latest.log)

**Comment by eutro** [comment]
The main issue is that you were using the normal GTCE version with GTCEu.
