### ISSUE TITLE
good job

### ISSUE THREAD

**Issue by huneau** [eutropius225/MultiblockTweaker#4]
Your work is pretty impressive and should be into GTCE and not out of the box. (with the new dev it should be doable)
I dont know if you will maintain your code properly but if you want and if GTCE doesnt wants your code (in case you dont want to code anymore) I can merge your code into mine :).

**Comment by eutro** [comment]
I have no intentions to drop support, but if I do, you're free to fork it and distribute your own version, as per the [license](https://github.com/eutropius225/MultiblockTweaker/blob/master/LICENSE).

As for merging with base GTCE, I don't think that's the right way forward, but thanks for your praise.
